---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations: # Creating Internal LB
    service.beta.kubernetes.io/azure-load-balancer-internal: "true" 
  labels:
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: nginx
    tier: backend
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      volumes:
      - name: app
        persistentVolumeClaim:
          claimName: app-pvc
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: site.conf
      containers:
      - name: nginx
        image: demoacr.azurecr.io/hstoychev/endeva-demo-nginx:latest
        imagePullSecrets:
        - name: my-acr-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app
          mountPath: /app
        - name: config
          mountPath: /etc/nginx/conf.d         